### ISSUE TITLE
How to control the pull down refresh?

### ISSUE THREAD

**Issue by seekcx** [diegoveloper/flutter_stretchy_header#9]
Hello, this is a very nice widget, and I am using it in conjunction with the pull down refresh widget. But I don't know how to make them work together, do you have any examples about pull down refresh widget?

**Comment by diegoveloper** [comment]
@seekcx working on it , I'll use similar properties like the RefreshIndicator.

**Comment by diegoveloper** [comment]
@seekcx I sent some changes to `master` could you update your `pubspec.yaml` pointing directly to my repo  ?  Also check this new sample : https://github.com/diegoveloper/flutter_stretchy_header/blob/master/example/lib/main.dart#L246

```yaml
stretchy_header:
    git:
      url: git@bitbucket.org:diegoveloper/flutter_stretchy_header
```
